name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.3.0
        with:
          haxe-version: 4.2.2

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          
          install_with_retry() {
            for i in {1..5}; do
              haxelib install $1 $2 --quiet && break || sleep 5
            done
          }

          install_with_retry lime 7.9.0
          install_with_retry openfl 9.1.0
          haxelib --never install flixel 4.9.0 --quiet
          echo y | haxelib run lime setup
          install_with_retry flixel-tools 1.5.1
          install_with_retry flixel-ui 2.3.3
          install_with_retry hscript
          install_with_retry flixel-addons 2.10.0
          install_with_retry actuate
          
          haxelib git extension-webm https://github.com/HaxeExtension/extension-webm --quiet
          haxelib git faxe https://github.com/ashea-code/faxe --quiet
          haxelib git polymod https://github.com/FunkinCrew/polymod --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit --quiet
          haxelib list

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 7.9.0
          haxelib set openfl 9.1.0
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Rebuild extension-webm
        run: haxelib run lime rebuild extension-webm android
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: error
